### ISSUE TITLE
Using Vue Chartkick with Laravel

### ISSUE THREAD

**Issue by gilles6** [ankane/vue-chartkick#106]
I am using `vue-chartkick` with Laravel. I followed the [documentation](https://github.com/ankane/vue-chartkick#quick-start) to install it.
```
npm install vue-chartkick chart.js
```
Then, in `resources/js/app.js`:
```
import Chartkick from 'vue-chartkick'
import Chart from 'chart.js'

Vue.use(Chartkick.use(Chart))

...

const app = new Vue({
    el: '#app',
    router: router,
    vuetify: new Vuetify()
});
```

Then, when I put `<line-chart :data="{'2017-01-01': 11, '2017-01-02': 6}"></line-chart>` into a component, I get the following error in javascript console:
```
[Vue warn]: Unknown custom element: <line-chart> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Dashboard> at resources/js/components/backend/Dashboard.vue
       <VApp>
         <Root>
```

What is the correct way to register the component ?

**Comment by ankane** [comment]
Hey @gilles6, `Vue.use` should register the chart components. Check out the Contributing Guide for where to get additional help.
