### ISSUE TITLE
Vue3 Support

### ISSUE THREAD

**Issue by rcoundon** [ankane/vue-chartkick#107]
Hi. As the plugin installation and initialisation mechanisms in Vue3 have changed, is there a plan for a new release to incorporate this?  Vue3 is now in RC4 status so the API is now stable. Thanks

**Comment by ankane** [comment]
Hey @rcoundon, support will be added once Vue 3 is officially released.

**Comment by gplanansky** [comment]
Just tried the master (734154e) and vue3 (00a77dc) branches.  Thanks for the vue3 so quickly.   

Using the respective test/index.html files, and (via npm install; npm run build) the respective dist/vue-kickchart.js files, result:  the vue3 pie chart and map re-load every second;  the vue2 ones are fine.  Same result with Firefox 78.3.0esr (64-bit) and Chrome  85.0.4183.121 (Official Build) (64-bit), on OS X.

**Comment by ankane** [comment]
Hey @gplanansky, you should be able to use the `vue3` branch. The reload is expected - see the Reactivity section of the readme on that branch (I'm still deciding whether to keep the current hack, but it's been removed on that branch).

The current plan is for v0.7.0 to be Vue 2 + Chartkick 4 and v1.0.0 to be Vue 3 + Chartkick 4 (released at the same time). Chartkick 4 will be released when Chart.js 3 is released, which just had a beta3 release earlier today. However, if things take longer than expected, will reevaluate the plan.

**Comment by SudeepPatra3** [comment]
This code is not working in vue.js 3

**Comment by ankane** [comment]
Decided to move ahead with a new plan since things are taking longer than expected. Just released 1.0 with support for Vue 3 and will release 2.0 when Chart.js 3 / Chartkick 4 are released.
