### ISSUE TITLE
Library parameter has no effect

### ISSUE THREAD

**Issue by literakl** [ankane/vue-chartkick#113]
The documentation contains:

You can pass options directly to the charting library with:

`<line-chart :library="{backgroundColor: '#eee'}"></line-chart>`

I tried it but the background does not changes. See:

https://codesandbox.io/s/pensive-williamson-upohe?file=/src/components/HelloWorld.vue

![image](https://user-images.githubusercontent.com/6383287/98986764-9e03d100-2525-11eb-8244-a1d651dbe1e0.png)

**Comment by ankane** [comment]
Hey @literakl, Chart.js doesn't have an option for background color (see the Chart.js docs for the full list of options), but you use CSS to set it.

**Comment by literakl** [comment]
Hi, I can see such parameter in their doc:

https://www.chartjs.org/docs/latest/?h=background
data: {
        labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
        datasets: [{
            label: '# of Votes',
            data: [12, 19, 3, 5, 2, 3],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
