### ISSUE TITLE
Horizontal Stack Bar

### ISSUE THREAD

**Issue by adavie1** [ankane/vue-chartkick#114]
Having difficulty getting a horizontal stacked bar:
Very simple dataset:` ['Active', 90], ['Rejected', 3], ['Closed', 2]`
Using Chart.js had set options as follows (from Chart.js docs):
```
  options: {
        scales: {
          xAxes: [
            {
              stacked: true
            }
          ],
          yAxes: [
            {
              stacked: true
            }
          ]
        }
      } 
```
This is what I'm getting:
![image](https://user-images.githubusercontent.com/3030402/100107316-7bb66f80-2ea4-11eb-9f03-cbe26a770702.png)

I'd like all the data in one stacked bar. If possible with the text as a tooltip, but I'll take what I can get!
![image](https://user-images.githubusercontent.com/3030402/100107888-1ca52a80-2ea5-11eb-8628-7ce9089cba4b.png)

**Comment by ankane** [comment]
Hey @adavie1, unfortunately, I don't have the bandwidth to help with customizing charts. Please check out the Contributing Guide for where to get help.
