### ISSUE TITLE
how to use vuechartkick in nuxt js

### ISSUE THREAD

**Issue by ImalshaRathnaweera** [ankane/vue-chartkick#117]
I create vuechartkick plugin in /plugin/vue-chartkick.
```
import Vue from 'vue'
import VueChartkick from 'vue-chartkick'
import Chart from 'chart.js'

Vue.use(VueChartkick, { adapter: Chart })
``` 
Then I add the file path inside the plugins key of our nuxt.config.js.
```
plugins: [ 
    { src: './plugins/vue-chartkick.js', mode: 'client' }
  ],
```
nuxt template

```
 <div v-if="resultSet" class="pa-4 pa-md-8">
          <div class="border-light pa-4 pa-md-12">
            <client-only placeholder="loading...">
              <line-chart
                legend="bottom"
                :data="series(resultSet)"
              ></line-chart>
            </client-only>
          </div>
```
I received this error
```
[Vue warn]: Unknown custom element: <line-chart> - did you register the component correctly? For recursive components, make sure to provide the "name" option
```

**Comment by ankane** [comment]
Hey @ImalshaRathnaweera, Nuxt isn't officially supported, but that code looks right (just tried it with a fresh Nuxt app and it seems to work).

**Comment by ImalshaRathnaweera** [comment]
@ankane if vue.js support then, nuxt.js should be supported, right? vue.js support vuechartkick

**Comment by ankane** [comment]
It should work (and does when I tried it with a fresh app) but won't be tested regularly as part of the library and I won't be able to help debug issues. Check out the Contributing Guide for where to get help from the community.

**Comment by sehrixhshafeeq** [comment]
When I use chartkick in nuxt, I get error `No element with id chart-1`

**Comment by mehdinourollah** [comment]
I'm getting this Error: No element with id chart-1 and I want to some how be able to use something like try/catch to prevent my whole page to crash.
![image](https://user-images.githubusercontent.com/5097056/135484846-9b154f7b-260a-44a7-a0da-8e4cafbb1198.png)
