### ISSUE TITLE
en vue js con laravel no me funciona 

### ISSUE THREAD

**Issue by freeccboypooh** [ankane/vue-chartkick#118]
Hi, este es el error que me da 

[Vue warn]: Error in render: "TypeError: Object(...) is not a function"

found in

---> <BarChart>
       <VentasEst> at resources/js/components/VentasEst.vue
         <App> at resources/js/App.vue
           <Root>
warn @ vue.common.dev.js?4650:630
logError @ vue.common.dev.js?4650:1889
globalHandleError @ vue.common.dev.js?4650:1884
handleError @ vue.common.dev.js?4650:1844
Vue._render @ vue.common.dev.js?4650:3549
updateComponent @ vue.common.dev.js?4650:4063
get @ vue.common.dev.js?4650:4474
Watcher @ vue.common.dev.js?4650:4463
mountComponent @ vue.common.dev.js?4650:4070
Vue.$mount @ vue.common.dev.js?4650:9040
Vue.$mount @ vue.common.dev.js?4650:11940
init @ vue.common.dev.js?4650:3121
createComponent @ vue.common.dev.js?4650:5969
createElm @ vue.common.dev.js?4650:5916
createChildren @ vue.common.dev.js?4650:6044
createElm @ vue.common.dev.js?4650:5945
createChildren @ vue.common.dev.js?4650:6044
createElm @ vue.common.dev.js?4650:5945
createChildren @ vue.common.dev.js?4650:6044
createElm @ vue.common.dev.js?4650:5945
patch @ vue.common.dev.js?4650:6466
Vue._update @ vue.common.dev.js?4650:3942
updateComponent @ vue.common.dev.js?4650:4063
get @ vue.common.dev.js?4650:4474
Watcher @ vue.common.dev.js?4650:4463
mountComponent @ vue.common.dev.js?4650:4070
Vue.$mount @ vue.common.dev.js?4650:9040
Vue.$mount @ vue.common.dev.js?4650:11940
init @ vue.common.dev.js?4650:3121
merged @ vue.common.dev.js?4650:3304
createComponent @ vue.common.dev.js?4650:5969
createElm @ vue.common.dev.js?4650:5916
createChildren @ vue.common.dev.js?4650:6044
createElm @ vue.common.dev.js?4650:5945
patch @ vue.common.dev.js?4650:6466
Vue._update @ vue.common.dev.js?4650:3942
updateComponent @ vue.common.dev.js?4650:4063
get @ vue.common.dev.js?4650:4474
Watcher @ vue.common.dev.js?4650:4463
mountComponent @ vue.common.dev.js?4650:4070
Vue.$mount @ vue.common.dev.js?4650:9040
Vue.$mount @ vue.common.dev.js?4650:11940
init @ vue.common.dev.js?4650:3121
createComponent @ vue.common.dev.js?4650:5969
createElm @ vue.common.dev.js?4650:5916
patch @ vue.common.dev.js?4650:6505
Vue._update @ vue.common.dev.js?4650:3942
updateComponent @ vue.common.dev.js?4650:4063
get @ vue.common.dev.js?4650:4474
Watcher @ vue.common.dev.js?4650:4463
mountComponent @ vue.common.dev.js?4650:4070
Vue.$mount @ vue.common.dev.js?4650:9040
Vue.$mount @ vue.common.dev.js?4650:11940
eval @ app.js?6d40:17
./resources/js/app.js @ app.js:2721
__webpack_require__ @ app.js:20
0 @ app.js:3222
__webpack_require__ @ app.js:20
(anonymous) @ app.js:84
(anonymous) @ app.js:87
Show 30 more frames
vue.common.dev.js?4650:1893 TypeError: Object(...) is not a function
    at Proxy.render (vue-chartkick.esm.js?d842:23)
    at VueComponent.Vue._render (vue.common.dev.js?4650:3547)
    at VueComponent.updateComponent (vue.common.dev.js?4650:4063)
    at Watcher.get (vue.common.dev.js?4650:4474)
    at new Watcher (vue.common.dev.js?4650:4463)
    at mountComponent (vue.common.dev.js?4650:4070)
    at VueComponent.Vue.$mount (vue.common.dev.js?4650:9040)
    at VueComponent.Vue.$mount (vue.common.dev.js?4650:11940)
    at init (vue.common.dev.js?4650:3121)
    at createComponent (vue.common.dev.js?4650:5969)
logError @ vue.common.dev.js?4650:1893
globalHandleError @ vue.common.dev.js?4650:1884
handleError @ vue.common.dev.js?4650:1844
Vue._render @ vue.common.dev.js?4650:3549
updateComponent @ vue.common.dev.js?4650:4063
get @ vue.common.dev.js?4650:4474
Watcher @ vue.common.dev.js?4650:4463
mountComponent @ vue.common.dev.js?4650:4070
Vue.$mount @ vue.common.dev.js?4650:9040
Vue.$mount @ vue.common.dev.js?4650:11940
init @ vue.common.dev.js?4650:3121
createComponent @ vue.common.dev.js?4650:5969
createElm @ vue.common.dev.js?4650:5916
createChildren @ vue.common.dev.js?4650:6044
createElm @ vue.common.dev.js?4650:5945
createChildren @ vue.common.dev.js?4650:6044
createElm @ vue.common.dev.js?4650:5945
createChildren @ vue.common.dev.js?4650:6044
createElm @ vue.common.dev.js?4650:5945
patch @ vue.common.dev.js?4650:6466
Vue._update @ vue.common.dev.js?4650:3942
updateComponent @ vue.common.dev.js?4650:4063
get @ vue.common.dev.js?4650:4474
Watcher @ vue.common.dev.js?4650:4463
mountComponent @ vue.common.dev.js?4650:4070
Vue.$mount @ vue.common.dev.js?4650:9040
Vue.$mount @ vue.common.dev.js?4650:11940
init @ vue.common.dev.js?4650:3121
merged @ vue.common.dev.js?4650:3304
createComponent @ vue.common.dev.js?4650:5969
createElm @ vue.common.dev.js?4650:5916
createChildren @ vue.common.dev.js?4650:6044
createElm @ vue.common.dev.js?4650:5945
patch @ vue.common.dev.js?4650:6466
Vue._update @ vue.common.dev.js?4650:3942
updateComponent @ vue.common.dev.js?4650:4063
get @ vue.common.dev.js?4650:4474
Watcher @ vue.common.dev.js?4650:4463
mountComponent @ vue.common.dev.js?4650:4070
Vue.$mount @ vue.common.dev.js?4650:9040
Vue.$mount @ vue.common.dev.js?4650:11940
init @ vue.common.dev.js?4650:3121
createComponent @ vue.common.dev.js?4650:5969
createElm @ vue.common.dev.js?4650:5916
patch @ vue.common.dev.js?4650:6505
Vue._update @ vue.common.dev.js?4650:3942
updateComponent @ vue.common.dev.js?4650:4063
get @ vue.common.dev.js?4650:4474
Watcher @ vue.common.dev.js?4650:4463
mountComponent @ vue.common.dev.js?4650:4070
Vue.$mount @ vue.common.dev.js?4650:9040
Vue.$mount @ vue.common.dev.js?4650:11940
eval @ app.js?6d40:17
./resources/js/app.js @ app.js:2721
__webpack_require__ @ app.js:20
0 @ app.js:3222
__webpack_require__ @ app.js:20
(anonymous) @ app.js:84
(anonymous) @ app.js:87
Show 29 more frames
vue.common.dev.js?4650:630 [Vue warn]: Error in mounted hook: "Error: No element with id chart-1"

found in

---> <BarChart>
       <VentasEst> at resources/js/components/VentasEst.vue
         <App> at resources/js/App.vue
           <Root>
warn @ vue.common.dev.js?4650:630
logError @ vue.common.dev.js?4650:1889
globalHandleError @ vue.common.dev.js?4650:1884
handleError @ vue.common.dev.js?4650:1844
invokeWithErrorHandling @ vue.common.dev.js?4650:1867
callHook @ vue.common.dev.js?4650:4216
insert @ vue.common.dev.js?4650:3142
invokeInsertHook @ vue.common.dev.js?4650:6337
patch @ vue.common.dev.js?4650:6554
Vue._update @ vue.common.dev.js?4650:3942
updateComponent @ vue.common.dev.js?4650:4063
get @ vue.common.dev.js?4650:4474
Watcher @ vue.common.dev.js?4650:4463
mountComponent @ vue.common.dev.js?4650:4070
Vue.$mount @ vue.common.dev.js?4650:9040
Vue.$mount @ vue.common.dev.js?4650:11940
eval @ app.js?6d40:17
./resources/js/app.js @ app.js:2721
__webpack_require__ @ app.js:20
0 @ app.js:3222
__webpack_require__ @ app.js:20
(anonymous) @ app.js:84
(anonymous) @ app.js:87
vue.common.dev.js?4650:1893 Error: No element with id chart-1
    at BarChart.Chart (chartkick.js?50d1:2080)
    at new BarChart (chartkick.js?50d1:2293)
    at VueComponent.updateChart (vue-chartkick.esm.js?d842:85)
    at VueComponent.mounted (vue-chartkick.esm.js?d842:69)
    at invokeWithErrorHandling (vue.common.dev.js?4650:1859)
    at callHook (vue.common.dev.js?4650:4216)
    at Object.insert (vue.common.dev.js?4650:3142)
    at invokeInsertHook (vue.common.dev.js?4650:6337)
    at Vue.patch [as __patch__] (vue.common.dev.js?4650:6554)
    at Vue._update (vue.common.dev.js?4650:3942)

Thanks!

**Comment by ankane** [comment]
Hey @freeccboypooh, thanks for the report. Unfortunately, I'm not sure how to reproduce. What versions of Vue.js and Vue Chartkick are you on?

**Comment by freeccboypooh** [comment]
este es un video mio explicando lo mas simple posible un midleware pero basado en este video puedes tener Larabel y Vue js funcionando juntos, quiza mejor hago un video explicando como correr Vue js  2.x con laravel  quiza asi reproduces las condiciones y hacer que funcione tu graficador que me parece mucho muy simple pero no funciona en vue js con larabel
https://youtu.be/kT-eMPudaxU

**Comment by ankane** [comment]
I think the issue may be it's trying to do server-side rendering rather than client-side. Also, with Vue.js 2, double check you're on Vue Chartkick 0.6.1 or earlier.
