### ISSUE TITLE
Geo chart and timeline does not work

### ISSUE THREAD

**Issue by jonelorentzen** [ankane/vue-chartkick#119]
Hi,

when I try to add any of the Google chart, example :<geo-chart :data="[['United States', 44], ['Germany', 23], ['Brazil', 22]]"></geo-chart>. I only get an empty chart, is it something wrong with the Goole charts?

Thanks!

**Comment by ankane** [comment]
Hey @jonelorentzen, are there any errors in the JavaScript console? Also, what's `:data` look like?

**Comment by jonelorentzen** [comment]
In the template I have <geo-chart :data="[['United States', 44], ['Germany', 23], ['Brazil', 22]]"></geo-chart>. I also mounted this "let recaptchaScript = document.createElement('script')
      recaptchaScript.setAttribute('src', "https://www.gstatic.com/charts/loader.js")
      document.head.appendChild(recaptchaScript)" in the component. My whole page goes white and I have added screenshot of the errors I get. It might be something wrong with the way I use it. Do you have any idea?
<img width="650" alt="Skjermbilde 2021-03-18 kl  12 52 01" src="https://user-images.githubusercontent.com/54357242/111621874-c60f8380-87e8-11eb-916b-762d61797e04.png">

**Comment by jonelorentzen** [comment]
I have also added Chartkick.configure({language: "de", mapsApiKey: "..."}) with my key.

**Comment by jonelorentzen** [comment]
Im stupid, the error was because my component was called GeoChart... Changed it to GeoChartComponent and it worked :) Thanks for great charts man <3
