### ISSUE TITLE
[Idea] Add Custom Label to Pie Chart Legend

### ISSUE THREAD

**Issue by dhimasyoga16** [ankane/vue-chartkick#121]
I found that Chartkick's awesome. But i think a new little feature need to be added.

![image](https://user-images.githubusercontent.com/43445454/126732305-321e59eb-deee-4fb2-b13c-5edcdc17cea8.png)

On the image above, i want to add custom label to the legend, say i want to make the label into **Magang 10%**, **Kelas 8%** and so on, **without affecting the tooltip value** when the pie is being hovered. Because in the current version of chartkick if i make the legend label into **Magang 10%** it will also affecting the tooltip value, the tooltip will become "Magang 10%: Rp 235.000"

I think it's a little bit helpful, because i need to show the value of the income amount of each category when i'm hovering the pie, while the label shows the percentage of each category.

Sorry for bad English, but i hope you understand what i mean. Thanks in advance!

**Comment by dhimasyoga16** [comment]
Or maybe Chartkick can adapt the Chart.js's custom tooltip feature, here's the [link](https://www.chartjs.org/docs/latest/samples/tooltip/content.html)

**Comment by ankane** [comment]
Hey @dhimasyoga16, I haven't tried this specific customization, but you should be able to use the `library` option for features available in the underlying charting library.
