### ISSUE TITLE
[Idea] Support for WordTree and other charts of Google charts

### ISSUE THREAD

**Issue by ManasMadrecha** [ankane/vue-chartkick#123]
Hi, 

Vue-Chartkick has really made it super easy to add pie-charts and normal axis-based charts of Google Charts, even in markdown (esp. Nuxt Content)

So, can we kindly have components for WordTree and other charts like Org Chart, etc. as well?

**Comment by ankane** [comment]
Hey @ManasMadrecha, thanks for the suggestion. I don't plan to add/support any new chart types right now, but you could fork this/Chartkick.js to add them to your projects.
