### ISSUE TITLE
Vue 2 - Unknown adapter  0.6.1

### ISSUE THREAD

**Issue by julianodev** [ankane/vue-chartkick#124]
Hi,

Hi, I'm trying to use vue 2, but I'm getting this error message, can you help me?

![image](https://user-images.githubusercontent.com/20190078/151288826-b64eb1f4-de42-4d7b-844b-3922534ca4fb.png)

Thanks!

**Comment by Youdaman** [comment]
I have the same issue.

Got it to work with the Highcharts instructions though: https://github.com/ankane/vue-chartkick/blob/v0.6.1/README.md#highcharts

**Comment by dave-alvarez** [comment]
I was able to fix this by installing version 2.9.4 of Chart.js. Looks like v3 was not out yet when 0.6.1 of vue-chartkick was released.

**Comment by Youdaman** [comment]
> I was able to fix this by installing version 2.9.4 of Chart.js. Looks like v3 was not out yet when 0.6.1 of vue-chartkick was released.

Excellent! This fixed it for me, thank you @dave-alvarez

**Comment by ankane** [comment]
As @dave-alvarez mentioned, Vue Chartkick 0.6.1 requires Chart.js 2. Just pushed a new branch with updated instructions and updated the link in the readme.

```sh
npm install vue-chartkick@0.6.1 chart.js@2
```
