### ISSUE TITLE
RESOLVED Can you give a webpack example?

### ISSUE THREAD

**Issue by reillychase** [ankane/vue-chartkick#14]
Hi sorry for newb question but your example only shows for a simple vue instance, but I am using webpack simple boilerplate and I cant get it to work. I think I need to import the component? 

'[Vue warn]: Failed to mount component: template or render function not defined.'

```

<script>
import Chartkick from 'chartkick'
import VueChartkick from 'vue-chartkick'
import Chart from 'chart.js'
Vue.use(VueChartkick, { Chartkick })

import axios from 'axios';


export default {

  name: 'analytics',
  data: () => ({
   chartData: [["Jan", 4], ["Feb", 2], ["Mar", 10], ["Apr", 5], ["May", 3]]


  })
}
</script>

```

**Comment by reillychase** [comment]
Resolved:
Just had to add this to "main.js" instead of myChart.vue

```import Chartkick from 'chartkick'
import VueChartkick from 'vue-chartkick'
import Chart from 'chart.js'
Vue.use(VueChartkick, { Chartkick })```

**Comment by ankane** [comment]
@reillychase glad you figured it out.
