### ISSUE TITLE
Support for combo chart?

### ISSUE THREAD

**Issue by reillychase** [ankane/vue-chartkick#15]
Hi, is there support for having both a line chart on top of a bar chart?

**Comment by ankane** [comment]
Hey @reillychase, Chartkick doesn't support combo charts right now.

**Comment by kjmtrue** [comment]
Please support combo chart.
Thank you!

**Comment by travisstaloch** [comment]
Are there any plans to add support for combo charts? I'm hoping to use this with a google charts combo candlestick and line chart for some financial data.  I might be able help code a solution for this if its possible.  Thanks for this great project!

**Comment by travisstaloch** [comment]
I tried forking the project and adding a simple entries to src/index.js
```js
createComponent(Vue, 'candlestick-chart', Chartkick.CandlestickChart)
createComponent(Vue, 'combo-chart', Chartkick.ComboChart)
```
but getting the error:
> ypeError: r is not a constructor
    at VueComponent.mounted (react-chartkick.min.js:8)
    at callHook (vue.js:2921)
    at Object.insert (vue.js:4152)
    at invokeInsertHook (vue.js:5947)
    at Vue.patch [as __patch__] (vue.js:6166)
    at Vue._update (vue.js:2660)
    at Vue.updateComponent (vue.js:2788)
    at Watcher.get (vue.js:3140)
    at new Watcher (vue.js:3129)
    at mountComponent (vue.js:2795)

Any idea what other steps I need to take to be able to use these types of charts?

**Comment by ankane** [comment]
Chartkick doesn't support either of those chart types, and isn't accepting new types at the moment. I'd recommend using Google Charts directly.
