### ISSUE TITLE
Support for multiple axis?

### ISSUE THREAD

**Issue by reillychase** [ankane/vue-chartkick#16]
Here are some options I was using with Google Charts before I converted my site to VueJS. I haven't been able to figure out to use them with this library yet, is it possible?

This is from a combo chart, but I'm fine with using line-chart in this library if I can get my second axis to be different from the first

```
options = {


           seriesType: 'bars',    
 
            series: {

              1: {side: 'right', type: "line", targetAxisIndex:1}, // Right y-axis.
              2: {targetAxisIndex:0},
            },
            
              axes: {
            y: {
      				
              1: {side: 'right'} // Right y-axis.
            }
          },

          colors: ["lightblue", "green"],};     
```

**Comment by ankane** [comment]
Hey @reillychase, I'm not sure if it's possible right now, but first class support is on the todo list. You can follow along at: https://github.com/ankane/chartkick.js/issues/79
