### ISSUE TITLE
Feature request: emit events

### ISSUE THREAD

**Issue by ImreC** [ankane/vue-chartkick#17]
Hi,

I gave vue-chartkick a spin the last couple of days and so far it works great. However, what really would be a great feature for me is that when you click any of the chart parts it would emit an event. In that way you can also easily build charts that respond on clicks (for example, add a filter on a certain part of the data when you click that piece of the pie). Thanks for this module!

Cheers

**Comment by ImreC** [comment]
Did some additional research. Apparently chartjs offers an built in onclick event which emits most of the data required. See answer here. https://stackoverflow.com/a/41870115/4462086. Having this as a standard emitted event in Vue would just offer an enormous range of extra possibilities with vue-chartkick.

**Comment by ankane** [comment]
Hey @ImreC, thanks for the suggestion 👍  You can pass options to Chart.js with the `library` option. See the readme for how to use it.

**Comment by Raystar2312** [comment]
Hi,
I am currently facing the same issue. I would like to call a function when I click on a marker on the Geo Chart.
Has this functionality been implemented since ?
