### ISSUE TITLE
Error: No element with id users-chart

### ISSUE THREAD

**Issue by toicodedoec** [ankane/vue-chartkick#19]
I follow the setup guidance & add the following line into my html file:
`<line-chart id="users-chart" width="800px" height="500px"></line-chart> `

However, when starting up, it says the error
`Error: No element with id users-chart`

After for a while of researching, I still can't solve it T.T

Can you give me any idea?

**Comment by ankane** [comment]
Hey @toicodedoec, can you create a JSFiddle to reproduce?

**Comment by mehdinourollah** [comment]
![image](https://user-images.githubusercontent.com/5097056/135484966-557320d2-d4f1-4160-a0ac-cb16677a303b.png)

Yet I'm getting this error and whole page crashes just for this component. Can you tell me how to prevent such things like a exception handling approach or ...

**Comment by atjpatatatj** [comment]
Same issue here.
Vue 3 + TS, sad I can't use chartkick
