### ISSUE TITLE
Render Geo Chart on state change

### ISSUE THREAD

**Issue by hunterway55** [ankane/vue-chartkick#2]
Hello.
Love this package.
It works really well with a line chart.
When I try using a geo chart which the data come from vuex state.
It wont update when the state changes?

I have a watch that watches a drop down
```
  watch: {
    product: function(product) {
      this.getProductByCountry(product);
    },
  },
```
and a computed which maps the state
```
  computed: {
    ...mapState({
      productbycountry: state => state.analytics.productsbycountry,
    }),
  },
```
and this is my geo chart
`<geo-chart :data="productbycountry" id="geo"></geo-chart>
`
When I change the product, the geo chart does not update.

It works with the line chart.

Any ideas on how I can get my geo-chart to update when i can the product?

Much Appreciated

**Comment by ankane** [comment]
Hey @hunterway55, thanks for reporting. I'm able to reproduce, but not sure of the cause. Chartkick is definitely refreshing the chart when the data updates, but it's not reflecting.

**Comment by hunterway55** [comment]
I noticed that to, I was able to get the chart to reflect the new data if i navigate to a new route then back to route chart is on. 
I have been trying to simulate this behaviour through clicking a button but no luck. 
Would exposing the render-Chart method to the parent help us?

**Comment by hunterway55** [comment]
Thank-you for the change, could you please update the version and so that it is updated on npm :)

**Comment by ankane** [comment]
The latest commit is for code quality. It doesn't fix the issue.

**Comment by ankane** [comment]
Hey @hunterway55, I tested this again just now and it works. May have been a fix by Google, but unsure.
