### ISSUE TITLE
How to change color tooltip in pie-chart

### ISSUE THREAD

**Issue by kjmtrue** [ankane/vue-chartkick#21]
I don't know why my tooltip font color is gray.

I try add config follow [document](http://www.chartjs.org/docs/latest/configuration/tooltip.html) like this. 

```javascript
Chart.defaults.global.tooltips.titleFontColor = "#fff";
Chart.defaults.global.tooltips.bodyFontColor = "#fff";
Chart.defaults.global.tooltips.footerFontColor = "#fff";
Chart.defaults.global.tooltips.multiKeyBackground = "#fff";
```
But it not working

![2017-10-01_131505](https://user-images.githubusercontent.com/9027134/31052306-2b805636-a6ab-11e7-99ee-88592cde19be.png)

**Comment by ankane** [comment]
Hey @kjmtrue, this is due to https://github.com/chartjs/Chart.js/issues/4741. I'd suggest downgrading to Chart.js 2.6 for now.

**Comment by ankane** [comment]
Chart.js 2.7.1 fixes this.
