### ISSUE TITLE
Geo Charts - States within one country

### ISSUE THREAD

**Issue by adavie1** [ankane/vue-chartkick#23]
Brilliant library!
Got a question, how do I display the states within a country?

I've got the [ISO codes list](https://en.wikipedia.org/wiki/ISO_3166-2%3aMY) Google uses.

How do I tell `<geo-chart ... >`  which country to select?

I've already tried this:

`  <geo-chart :data="[['MY-14', 44], ['MY-12', 23], ['MY-10', 22]]"></geo-chart>`

Which doesn't work.

Thanks in advance.

**Comment by ankane** [comment]
Hey @adavie1, you can use the `library` option for this.

```vue
<geo-chart :data="data" :library="{region: 'US', resolution: 'provinces'}"></geo-chart>
```

See the Google Charts docs for more info/options.

**Comment by adavie1** [comment]
Thanks! I'll give that a whirl.

**Comment by adavie1** [comment]
Aplogies for the slow reply- I've been tied up on other matters. I'll either confirm or close this within two days. Thanks for your patience.

**Comment by adavie1** [comment]
Hi, finally got some time to look at this:
This is what I have, the map shows up, but without any data points.

What am I doing wrong?

Thanks in advance.

```
<template>
  <div>

    <div id="results"></div>  

 <!--   <geo-chart :data="[['MY-14', 44], ['MY-12', 23], ['MY-10', 22]]"></geo-chart>  -->

 <geo-chart :data="mapData" :library="{region: 'MY', resolution: 'provinces'}"></geo-chart>
 
  </div>
</template>

<script>
  import Vue from 'vue'
  
  import Chartkick from 'chartkick'
  import VueChartkick from 'vue-chartkick'

  Vue.use(VueChartkick, { Chartkick })

  export default {
    name: 'google-map',

    data () {
      return {
        mapData: [
         [{v: 'MY-14', f: ' Wilayah Persekutuan Kuala Lumpur'}, 42],
         [{v: 'MY-15', f: ' Wilayah Persekutuan Labuan'}, 57],
         [{v: 'MY-16', f: ' Wilayah Persekutuan Putrajaya'}, 38],
         [{v: 'MY-01', f: ' Johor'}, 82],
         [{v: 'MY-02', f: ' Kedah'}, 46],
         [{v: 'MY-03', f: ' Kelantan'}, 51],
         [{v: 'MY-04', f: ' Melaka'}, 72],
         [{v: 'MY-05', f: ' Negeri Sembilan'}, 16],
         [{v: 'MY-06', f: ' Pahang'}, 2],
         [{v: 'MY-08', f: ' Perak'}, 87],
         [{v: 'MY-09', f: ' Perlis'}, 29],
         [{v: 'MY-07', f: ' Pulau Pinang'}, 49],
         [{v: 'MY-12', f: ' Sabah'}, 26],
         [{v: 'MY-13', f: ' Sarawak'}, 94],
         [{v: 'MY-10', f: ' Selangor'}, 35],
         [{v: 'MY-11', f: ' Terengganu'}, 79]
        ],
        mapOptions: this.options
      }
    }

  }
</script>

<style lang="scss">
  @import "../../../sass/_variables.scss";

  .google-map {
    height: 100%;
  }
</style>
```

**Comment by ankane** [comment]
@adavie1 `mapData` is not in a format supported by Chartkick. Try replacing the `{v: 'MY-NN', f: ' ...'}` objects with the string `MY-NN`.

**Comment by adavie1** [comment]
Hi @ankane, thanks for the reply.

I was using the format from the Google Charts example.

This worked.

```
     mapData: [
         ['MY-14', 42],
         ['MY-15', 57],
         ['MY-16', 38],
         ['MY-01', 82],
         ['MY-02', 46],
         ['MY-03', 51],
         ['MY-04', 72],
         ['MY-05', 16],
         ['MY-06', 2],
         ['MY-08', 87],
         ['MY-09', 29],
         ['MY-07', 49],
         ['MY-12', 26],
         ['MY-13', 94],
         ['MY-10', 35],
         ['MY-11', 79]
]
```
However, I still have one question, how do I get the labels to refer to the state name, rather than the short code?

Brilliant component by the way!

**Comment by ankane** [comment]
@adavie1 Replacing the short code with the label may work. If not, I'd recommend switching to Google Charts directly.
