### ISSUE TITLE
Add "points" property so line-chart can be without points

### ISSUE THREAD

**Issue by KlausSchaefersAtWork** [ankane/vue-chartkick#24]
Could you please add a "points" property, so the line-chart can be rendered without the line points.

var chartId = 1

var createComponent = function(Vue, tagName, chartType) {
  var chartProps = [
    "colors", "curve", "discrete", "donut", "download", "label",
    "legend", "library", "max", "min", "points", "refresh",
    "stacked", "title", "xtitle", "xtype", "ytitle", "points"
  ]
  Vue.component(tagName, {
    props: ["data", "id", "width", "height"].concat(chartProps),
    render: function(createElement) {
      return createElement(
        "div",
        {
          attrs: {
            id: this.chartId
          },
          style: this.chartStyle
        },
        ["Loading..."]
      );
    },

**Comment by ankane** [comment]
Hey @KlausSchaefersAtWork, `points` is already there: https://github.com/ankane/vue-chartkick/blob/9f0f131aa43b2fde2935132d72ef677264a5a031/index.js#L14
