### ISSUE TITLE
How to set background color to transparent color?

### ISSUE THREAD

**Issue by pirmax** [ankane/vue-chartkick#25]
Hi,

How to set background color to transparent color?

`<area-chart :data="areaChartData" :download="true"></area-chart>`

Thanks!

**Comment by ankane** [comment]
Hey @pirmax, for Chart.js, it already is. For Google Charts and Highcharts, you'll need to use the `library` option.

**Comment by ankane** [comment]
Cleaning up stale issues (no response)

**Comment by GeorgeZoum** [comment]
Is there an example for each one? Chart.js, Highcharts, and Google Charts? Just to see them all in one place?

**Comment by ankane** [comment]
Not that I'm aware of.

**Comment by jbuyu** [comment]
Hi @pirmax , how can I override the background colors please?
