### ISSUE TITLE
is there a way to change axis language?

### ISSUE THREAD

**Issue by Bu3a3a** [ankane/vue-chartkick#28]
Thank you for your work.

I've encountered a problem. Dates are converted in English month names automatically. Is there a way to change axis labels' language? Or maybe I can prevent this date-to-month-name convertion somehow?

**Comment by ankane** [comment]
Hey @Bu3a3a, one option is to use `:discrete=true` to prevent dates from being parsed and formatted.

If you use Google Charts, another option is to set `Chartkick.configure({language: "de"});` after the import.

**Comment by Bu3a3a** [comment]
Thanks a lot!

**Comment by pavermakov** [comment]
@ankane If I put this code `Chartkick.configure({language: "de"});` after the import, I get an error that `configure is not a function`

**Comment by ankane** [comment]
Chartkick is no longer exposed, so that'll no longer work. Happy to accept a PR for something like:

```js
VueChartkick.configure({language: "de"})
```

which just calls Chartkick behind the scenes.
