### ISSUE TITLE
column-chart multi columns

### ISSUE THREAD

**Issue by JoannesCeyrat** [ankane/vue-chartkick#31]
Hello Ankane.
I don't find how to set data to display columns with 2 or more sub-columns per column.
For exemple incomes/outcomes per month.

In googles charts the data are : 
var data = google.visualization.arrayToDataTable([
          ['Year', 'Sales', 'Expenses', 'Profit'],
          ['2014', 1000, 400, 200],
          ['2015', 1170, 460, 250],
          ['2016', 660, 1120, 300],
          ['2017', 1030, 540, 350]
        ]);
 It would be great if you could tell me and usefull also for others.
Thank you.
Joannes

**Comment by ankane** [comment]
Hey @JoannesCeyrat, it sounds like you want a chart with multiple series. Try:

```javascript
[
  {name: 'Sales', data: {2014: 1000, 2015: 1170}},
  {name: 'Expenses', data: {2014: 400, 2015: 460}},
  {name: 'Profit', data: {2014: 20, 2015: 250}}
]
```

**Comment by JoannesCeyrat** [comment]
YES !
Thank you very much!

**Comment by ankane** [comment]
Hey @mehdinourollah, there's an example in the readme in the "Charts" section.

**Comment by mehdinourollah** [comment]
> Hey @mehdinourollah, there's an example in the readme in the "Charts" section.

Dear @ankane I checked out the Docs and Readme  A LOT ! but the thing I was looking for wasn't in there ...I mean just a simple use case was [there](https://github.com/ankane/vue-chartkick#charts) but for example, for using the column-chart as 3D (or cluster IDK?) I needed to know how should it pass the data and what should be the structure of that like this 

> https://github.com/ankane/vue-chartkick/issues/31#issuecomment-367654786

 so If you don't mind please include more details in the Readme or the Documentations...I have to thank you again for contributing this valuable library 🙏🏻
