### ISSUE TITLE
line charts with null value

### ISSUE THREAD

**Issue by PedroRamosRguez** [ankane/vue-chartkick#34]
Hi, im using this awesome lib and i got a issue when im trying to show  a line charts with a null value. when the charts is rendered the line chart is cut. But, using Chartjs the chart is rendered without problem. Its possible to render the line chart with theese values?

```javascript
 prueba : [
    {name: 'prueba', data:{"Jan":12,"test":null,"Mar":23,"Abr":2,"Jun":55,"Jul":null,"Ago":123,"Sept":23,"Oct":1,"Nov":5,"Dic":53}}       
   ]
```
Here a screenshot with the result of rendered chart

![sin titulo](https://user-images.githubusercontent.com/14938442/37036644-30fd3e18-2148-11e8-9806-e23739c8a3e9.png)

**Comment by PedroRamosRguez** [comment]
OK I solved  seting in library option `spanGaps: true`. You can close this one.

COngratulation again for this awesome lib 👍

**Comment by ankane** [comment]
Great, glad you figured it out
