### ISSUE TITLE
[BarChart] Properties library 

### ISSUE THREAD

**Issue by fadzril** [ankane/vue-chartkick#36]
Hi, thanks for the wonderful plugins. Here, I'm trying to override some properties using `library`, sample code below:

```
<bar-chart 
  :data="[['Unknown', 300], ['Receiver', 500], ['Voters', 1000]]"
  :colors="['#209cee', '#01d1b2', '#ffde56']"
  :library="{'borderWidth': 0}" 
  :height="160"
  :legend="false" />
```

Seems like this particular chart can't pickup properties override for `library`/`colors`. Can someone point me to correct implementation, perhaps I've missed it from `docs`. Thanks

**Comment by ankane** [comment]
Hey @fadzril, the colors are for different series, not for different bars. The `library` option works, so not sure why you're not getting the results you're looking for.
