### ISSUE TITLE
Error Loading Chart: Cannot read property 'length' of undefined on :message="{empty: 'No data'}"

### ISSUE THREAD

**Issue by josephharveyangeles** [ankane/vue-chartkick#37]
I have this template.
```html
<pie-chart  :messages="{empty: 'No data'}" :legend="false" :donut="true" :data="chartData"/>
```

I change `chartData` dynamically by letting the user select a date and calling my backend for the data. Everything's fine until you do these steps:

1. `chartData` is null, `No data` is displayed.
2. `chartData` is not null (choose a date with data)
3. `chartData` is null, `No data` is displayed
4. `chartData` is not null.

Expected: Data is displayed.
Actual: `Error Loading Chart: Cannot read property 'length' of undefined`

Having this stacktrace:
```js
TypeError: Cannot read property 'length' of undefined
    at Object.acquireContext (platform.dom.js?0cdd:340)
    at Chart.construct (core.controller.js?821b:79)
    at new Chart (core.js?f88b:42)
    at drawChart (chartjs.js?949b:124)
    at Object.renderPieChart (chartjs.js?949b:435)
    at callAdapter (chartkick.js?f20b:175)
    at renderChart (chartkick.js?f20b:155)
    at PieChart.__render (chartkick.js?f20b:403)
    at errorCatcher (chartkick.js?f20b:36)
    at fetchDataSource (chartkick.js?f20b:53)
```

I have investigated and I think the problem is in this code:
```js
let drawChart = function(chart, type, data, options) {
  if (chart.chart) {
    chart.chart.destroy();
  } else {
    chart.element.innerHTML = "<canvas></canvas>";
  }
```
On step 2, `chart.chart` is undefined. It then creates `"<canvas></canvas>"` everything goes smoothly.
The problem is on step 3. `chart.chart` is not cleared or something so when step 4 comes in, `if (chart.chart)` returns `true`. Then the call to `chart.js`: 
```js
line 123: let ctx = chart.element.getElementsByTagName("CANVAS")[0];
```
returns `null`. and The chart constructor needs that to build new one. This thing on `platform.dom.js` fails: 
```js
line 340: acquireContext: function(item, config) {
		if (typeof item === 'string') {
			item = document.getElementById(item);
		} else if (item.length) {
			// Support for array based queries (such as jQuery)
			item = item[0];
		}
```

I tested just tested it with the following scenario too
1. `chartData` is not null
2. `chartData` is not null
`chart.chart` is destroyed, so everything fails again.

This only happens when I have that `messages` prop.
I'm using Google Chrome Version 63.0.3239.132

I think this is quite an easy fix, perhaps just always create the canvas on `drawChart()`
```js
let drawChart = function(chart, type, data, options) {
  if (chart.chart) {
    chart.chart.destroy();
  }
  chart.element.innerHTML = "<canvas></canvas>";
```

Or Idk. There might be a reason behind this.

_PS: Sorry for the long post, this was my first issue submission. Has always been on the sideline. I've always wanted to participate in the open source community. Just didn't have the confidence if I actually can._

**Comment by ankane** [comment]
Hey @josephharveyangeles, thanks for the detailed report 👍 and glad you decided to participate in open source! I went with the fix you suggested here: https://github.com/ankane/chartkick.js/commit/edae49c59a44239515029ee766274cf46d02f830
