### ISSUE TITLE
Uncaught RangeError: Maximum call stack size

### ISSUE THREAD

**Issue by shai-benshimol** [ankane/vue-chartkick#38]
Hii, 
I just get Uncaught RangeError: Maximum call stack size  when i use
<column-chart :data="[['Sun', 32], ['Mon', 46], ['Tue', 28]]"></column-chart>
Inside vue component

**Comment by ankane** [comment]
Hey @shai-benshimol, can you provide code to reproduce, as well as the stack trace?

**Comment by ankane** [comment]
Cleaning up stale issues
