### ISSUE TITLE
Line chart not using library prop

### ISSUE THREAD

**Issue by 00Rez** [ankane/vue-chartkick#41]
I've added a library prop e.g.: 
`<line-chart :data="..." :library="{ steppedLine: true }"></line-chart>`

Yet the options aren't reflected in the chart. I'm using a *line* chart. After looking at the dist files it seems the library options aren't merged? Whereas other charts merge the library options.

**Comment by ankane** [comment]
Check out https://github.com/ankane/chartkick.js/pull/90 for how to add library options within the `datasets` array.

**Comment by 00Rez** [comment]
Thanks @ankane  for the swift response. Works a treat.
