### ISSUE TITLE
Chartkick is undefined after update

### ISSUE THREAD

**Issue by e200** [ankane/vue-chartkick#44]
console logs `Chartkick is undefined ` after update

```json
"chartkick": "^2.3.5",
"vue-chartkick": "^0.2.2",
```

```javascript
import Vue from 'vue'
import VueChartkick from 'vue-chartkick'
import Chart from 'chart.js'

Vue.use(VueChartkick, {adapter: Chart})
```

**Comment by ankane** [comment]
Hey @e200, what’s the stack trace?

**Comment by ankane** [comment]
Think the problem is you’re on 0.2.2 but following instructions for the latest version (0.3.0).

**Comment by e200** [comment]
@ankane, it was really a problem with the package version.

Sorry, and thanks for the help.
