### ISSUE TITLE
Following "No Package Manager" instructions throws "Cannot read property 'adapter' of undefined"

### ISSUE THREAD

**Issue by langdonx** [ankane/vue-chartkick#46]
As titled, I tried to follow the [No Package Manger](https://github.com/ankane/vue-chartkick#no-package-manager) instructions:

https://jsfiddle.net/langdonx/o3hj0Lcu/

**Comment by langdonx** [comment]
Looks like it's fixed here... https://github.com/ankane/vue-chartkick/blob/master/src/index.js#L73

Any chance of a new release?

**Comment by ankane** [comment]
Released.
