### ISSUE TITLE
Library prop doesn't work (Google Charts)

### ISSUE THREAD

**Issue by PELEk** [ankane/vue-chartkick#5]
Library prop doesn't work at all using Google Charts (I haven't tested it with other libraries).

**Comment by ankane** [comment]
Hey @PELEk, can you give code to reproduce?

**Comment by PELEk** [comment]
@ankane Nevermind, I forgot I was loading chartjs in some old part of an app and after deleting it it works ;)

**Comment by ankane** [comment]
Glad it's working now.
