### ISSUE TITLE
multiple call of updated for each change in the dom leads to worse animation

### ISSUE THREAD

**Issue by dirk-ecker** [ankane/vue-chartkick#51]
Hi,
first vue-chartkick and chartkick itself is awesome an I like to use it.

I recently discovered some not so nice effect. The charts were updated for each single change in the actual page. That means if you use animation than you will discover that i.e. a pie chart is painted multiple times each time a little bit more. That looks ugly. The reason for this is, that a chart is painted in the method updated and not using a watch on the data. I thinks that would be the right implementation.

Kind regards
Dirk

**Comment by ankane** [comment]
Hey @dirk-ecker, not sure I follow. Can you share code to reproduce the issue? Also, if you have a suggested fix, happy to review a PR.

**Comment by ankane** [comment]
Fixed in https://github.com/ankane/vue-chartkick/commit/d3b0e42091cb7e1bf97fbb604249c5bb229207c9
