### ISSUE TITLE
The 'dataset' options have no effect

### ISSUE THREAD

**Issue by demestav** [ankane/vue-chartkick#54]
Using the following minimal example

`<line-chart :dataset="{borderWidth: 10}" :data="{'A': 44, 'B': 23, 'C': 60, 'D': 50}"></line-chart>`

the `boarderWidth` parameter does not change the line width, no matter what number is used.

**Comment by ankane** [comment]
Make sure you're using the master branch.

**Comment by demestav** [comment]
Thank you. I am using the 0.3.3 version from unpkg. Is this feature not implemented in that version?

**Comment by dirk-ecker** [comment]
@demestav Is dataset a property of the line-chart component. I can't find it. Maybe using library is the right choice.

**Comment by demestav** [comment]
@dirk-ecker Yes it is.

I built the project from source using the master branch as @ankane suggested, and works fine.
Closing this.
