### ISSUE TITLE
changes inside library property does not update the chart

### ISSUE THREAD

**Issue by dirk-ecker** [ankane/vue-chartkick#55]
Changes inside the library property does not trigger the update function for the chart because we shallow copy the properties in currentState and library is an object.

A workaround for this is to replace the complete object.
 
Example
---------
does not work:             
`this.options.scales.yAxes[0].type = (this.options.scales.yAxes[0].type === 'linear') ? 'logarithmic' : 'linear'
`

this works:
`this.options = {...this.options, scales: { yAxes: [{type: ((this.options.scales.yAxes[0].type === 'linear') ? 'logarithmic' : 'linear')}]}}`

**Comment by CrazyAlien1** [comment]
Same here, I had version 0.3.0 and was using a line <line-chart> to display dynamic data and once I updated to the last version 0.3.3 the graph only displayed if I completely changed the object (I think vue was doing re-rendering the component)

**Comment by ankane** [comment]
Hey @dirk-ecker and @CrazyAlien1, thanks for reporting 👍 It should be fixed on master. Can you give it a shot and let me know?

**Comment by ankane** [comment]
Released 0.4.0.
