### ISSUE TITLE
Properties

### ISSUE THREAD

**Issue by CrazyAlien1** [ankane/vue-chartkick#56]
Where can we see the full list of properties we can use?
I'm using line-chart and what I understand that belongs to Chart.js and I'm trying to use the property pointRadius so I can see big chunks of data without points only a line.
I've tried 
-> line-chart :pointRadius="0" :options="myOptions"
-> inside the options
-> using the property dataset

But none of those work.
Can you give a some some help pls?

**Comment by ankane** [comment]
Hey @CrazyAlien1, the full list is documented in the readme. For `pointRadius`, you'll need to use the `dataset` option, which is only available on master (not released). I'll push a new release once #55 is resolved.
