### ISSUE TITLE
ajax call is that possible ?

### ISSUE THREAD

**Issue by Tomarnst** [ankane/vue-chartkick#58]
Hi,

`<column-chart :data="some remote file" label="test" :library="{animation: {duration: 200 , easing: 'linear' }}"></column-chart>`

Just wondering if something like this is possible .. can someone supply an example how to do this.

Thanks!

**Comment by ankane** [comment]
Hey @Tomarnst, there's an example in the readme.

**Comment by Tomarnst** [comment]
@ankane 

Yep, sorry I see now ... I thought I didn't understand it due to a error I got by using
`<column-chart :data="some remote file"></column-chart>`
instead of ...
`<column-chart data="some remote file"></column-chart>`

Thanks again
