### ISSUE TITLE
render chart type by param string

### ISSUE THREAD

**Issue by giolvani** [ankane/vue-chartkick#60]
Could be possible render the graph by a custom string option?

to use something like this:
```
<chart type="column" :data="[['Sun', 32], ['Mon', 46], ['Tue', 28]]"></chart>
```

insted of:
```
<column-chart :data="[['Sun', 32], ['Mon', 46], ['Tue', 28]]"></column-chart>
```

**Comment by ankane** [comment]
Hey @giolvani, you can do this with Vue dynamic components: https://vuejs.org/v2/guide/components.html#Dynamic-Components

```vue
<component is="column-chart" :data="[['Sun', 32], ['Mon', 46], ['Tue', 28]]"></component>
```

**Comment by giolvani** [comment]
Tks so much @ankane. Sorry for do not find this at documentation.
