### ISSUE TITLE
Range for line-chart not used

### ISSUE THREAD

**Issue by focussing** [ankane/vue-chartkick#62]
Hi,

The following screenshot shows the problem...
The data array is like this

Array(10)
0:(2) [41.9148597753193, 204.501041326787, __ob__: Observer]
1:(2) [41.9291410552399, 212.497221871292, __ob__: Observer]
2:(2) [41.9433990735051, 217.11076727189, __ob__: Observer]
...
![schermafbeelding 2018-08-08 om 16 38 21](https://user-images.githubusercontent.com/26736152/43844258-916b613e-9b29-11e8-8f39-617ea5fe3c21.png)

**Comment by ankane** [comment]
Hey @focussing, can you explain the issue?

**Comment by focussing** [comment]
Hey @ankane, sorry for being not clear.
The x-axis is "date" or time, in stead of numbers as given in the dataset.

**Comment by ankane** [comment]
Line charts have a time x-axis by default. Use `xtype="number"` for a numeric x-axis.

**Comment by ankane** [comment]
Numeric axes should automatically be detected in the latest version.
