### ISSUE TITLE
Turning off line animation for HighCharts

### ISSUE THREAD

**Issue by vprewitt** [ankane/vue-chartkick#63]
Is there a way to turn of the line drawing animation, I have a line chart with constantly changing values and the animation is making it unreadable

I have tried a number of things with :library="chart: {animation: false}" etc on the <line-chart declaration where I bind it to the data but nothing seems to effect it 

Thanks 
Virgil

**Comment by sofger** [comment]
Hi Virgil!

```html
        <line-chart :library="{chart: {animation: false}, plotOptions: {series: {animation: {duration: 0}}}}" :data="chartData" />
```
Give it a try!

**Comment by vprewitt** [comment]
Thanks I will 

Virg
650-787-1075

**Comment by ankane** [comment]
Thanks for helping @sofger 👍
