### ISSUE TITLE
Two issues

### ISSUE THREAD

**Issue by AshwinTayson** [ankane/vue-chartkick#65]
Hi,

I didn't want to open two issues. My problems are as follows

1. There's no documentation regarding how to add google key to the chart(Geo chart) - **Question**
2. I have chartkick configured like this

Vue.use(VueChartkick) // Use google chart

I imported another user's component that uses Chartjs. Now all my google charts has become Chartjs charts. Is there a way to avoid this? - **Serious issue**

**Comment by ankane** [comment]
Your "serious issue" is a feature request. Please be constructive if you want to participate in the community.

**Comment by AshwinTayson** [comment]
_I imported another user's component that uses Chartjs. Now all my google charts has become Chartjs charts._

When using multiple libraries, using one shouldn't override the other. This is clearly a bug. Please be open to look at bugs, if not interested in solving them.
