### ISSUE TITLE
Multiple series suffix

### ISSUE THREAD

**Issue by benrolfe** [ankane/vue-chartkick#67]
When returning data for "multiple series", is it possible to return a suffix?

Ie: Can I return "minutes" for one series and "length" for another?

**Comment by ankane** [comment]
Hey @benrolfe, there's not a way to specify suffixes per series. I added a list of options per series to the docs: https://github.com/ankane/vue-chartkick/commit/09d190ba2cb7451ef914382961d5bf9bbbace5bb
