### ISSUE TITLE
How to include value for the legend for for bar, pie and donut?

### ISSUE THREAD

**Issue by adavie1** [ankane/vue-chartkick#69]
Is it possible to include the value in the legend text for the simple chart types like: bar, pie, line, etc.?

My users have been asking for that.

I'm using the **Charts.js** version of `vue-chartkick`.

Or is this a Charts.js issue?

**Comment by ankane** [comment]
Hey @adavie1, I'm not sure if Chart.js supports this. If so, you can use the `library` or `dataset` option for it.
