### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by maciz84** [ankane/vue-chartkick#70]
Hi,

Does anyone know how I can get this library to work with typescript. Keep getting:

Could not find a declaration file for module 'vue-chartkick'
Could not find a declaration file for module 'chart.js

Is there any .d.ts file someon hsa written I could use?

**Comment by maciz84** [comment]
Figured it out in the end

**Comment by maciz84** [comment]
Hi Guys,

I am sorry I didn't post the solution I fell asleep. But the solution is not really a solution as it is exactly as the documentation says on the vue-chartkick npm page. I was making a mistake in how I was using ChartJS which I had previously installed.

**Comment by maciz84** [comment]
If anyone has issues please let me know I will try and assist but all in all it works straight out of the box

**Comment by cnsmedia** [comment]
vue-chartkick/index.d.ts:

```
declare module "vue-chartkick" {
    import {PluginObject} from "vue";
    interface VueChartkickPlugin<T> extends PluginObject<T> {
        version: string;
        addAdapter: (library: any) => void
    }
    const VueChartkick: VueChartkickPlugin;
    export default VueChartkick;
}

```

To use it:

```
import VueChartkick from 'vue-chartkick';

Vue.use(VueChartkick, {adapter: Chart});
```

**Comment by cnsmedia** [comment]
I have submitted a pull request to DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33197

**Comment by whossname** [comment]
@ghost I'm pretty sure that type definition doesn't work if you are using Google charts instead of chart.js
