### ISSUE TITLE
Chart.js x-axis labels display issue

### ISSUE THREAD

**Issue by charlie965** [ankane/vue-chartkick#72]
On a time-based chart.js  line chart or area chart with multiple dates, only one date label shows in the far left corner of the x-axis on load. Sometimes, it even shows no labels at all. If I use hot reload during development, changes to the chart's attributes will sometime force it to reload to show the correct labels, but I'm stuck with the first one in production.

I've tried feeding specific configs into the 'library' attribute, but haven't found anything that fixes this.
Is there a way for me to access the chart by ID and force a chart.update() manually if this can't be done through configuration?

**Comment by ankane** [comment]
Hey @charlie965, can you put together a minimal example to demonstrate the issue?

**Comment by charlie965** [comment]
Sorry for the late response.  I was out of town but I'll try to get something together this week.

**Comment by charlie965** [comment]
https://jsfiddle.net/zdet1has/
After creating this example, I realized this must have something to do with webpack and Quasar framework. Not sure where to go from here.

**Comment by ankane** [comment]
The labels are good in the JSFiddle, yeah? I haven't used Quasar, so not sure what it could be.

**Comment by ankane** [comment]
Cleaning up stale issues
