### ISSUE TITLE
line chart scales always start at zero

### ISSUE THREAD

**Issue by cycloon** [ankane/vue-chartkick#73]
I tried vue-chartkick today and had a problem I did not have using Chart.js or Google Charts directly.
With vue-chartkick, (y-)scales of line charts always start at zero. Using the frameworks without vue, they all default to automatic scale sizes.

I tried to set library options: beginAtZero: false with no effect.

Finally I found a fix: if I set :min="null", the scale is back to full autoscale.

Example with defect: https://jsfiddle.net/4tv3Lwah/1/
Example with workaround: https://jsfiddle.net/93z6t08x/1/

As you might see, with the workaround, the scale starts at $10.

I am not so profound to suggest a fix, but somehow min: 0 seems to be added to the default props

**Comment by ankane** [comment]
Hey @cycloon, this is by design and documented in the Options section: https://github.com/ankane/vue-chartkick#options

Chartkick uses its own defaults rather than trying to match the charting libraries.
