### ISSUE TITLE
Place the printed percentage in each partition

### ISSUE THREAD

**Issue by OscarPrzLms** [ankane/vue-chartkick#76]
Hi!

How to make the printed percentage appear in each partition of piechart, barChart and ColumnChart. I work with vue.js. Please help.

 need to know what instruction to put inside the tag

<pie-chart :donut="false" :data="pieChartDistincion" :colors="['#28a745','#fd7e14','#17a2b8']" suffix="%"></pie-chart>

**Comment by ankane** [comment]
Hey @OscarPrzLms, please check out the Contributing Guide.
