### ISSUE TITLE
Can't show diffent values on one date

### ISSUE THREAD

**Issue by Tusko** [ankane/vue-chartkick#78]
Hello @ankane
Thank you for a great component.

I have an issue with the same date and different values.
My array is:

`[["22.06.2018","1.2"],["22.06.2018","1.58"],["30.01.2019","3.25"],["30.01.2019","0.85"],["30.01.2019","1.25"],["07.02.2019","2.58"]]`

And result is http://cl.ly/39d86705a639
So, chart shows only latest value by date.
How can I fix it?
Can you check it?

**Comment by ankane** [comment]
Hey @Tusko, by design, there can only be one value per date per series. Out of curiosity, what does it mean if a single date has two values, and how would you like it to appear?

**Comment by Tusko** [comment]
@ankane 
smth like this:
http://cl.ly/15a64b9e7988

**Comment by ankane** [comment]
Interesting... I don't think this is a very common need, so you'll probably want to use vue-chartjs instead.

**Comment by Tusko** [comment]
@ankane thank you.
I'll try it

**Comment by Tusko** [comment]
@ankane 
It works nice http://cl.ly/4d87f66f8701

Thank you so much!
