### ISSUE TITLE
How to using Multiple Libraries in vue

### ISSUE THREAD

**Issue by esa89** [ankane/vue-chartkick#80]
Hello thanks for awesome library !!

Im trying to use multiple library (google, chartjs, & highcharts) but its doesnt work. This is example of my code:
`
//main.js
import Vue from 'vue'
import VueChartkick from 'vue-chartkick'

Vue.use(VueChartkick, { adapter: Chart }, { adapter: Highcharts })
`
`
//chart.vue
<template>
    <pie-chart adapter="highcharts" :data="[['Blueberry', 44], ['Strawberry', 23]]"></pie-chart>
</template>
`
But highchart option is not show up.
Could you tell me the right way to use multiple library?

**Comment by ankane** [comment]
Hey @esa89, just released a new version for this. You can do:

```js
import Vue from 'vue'
import Chartkick from 'vue-chartkick'

// charting libraries
import Chart from 'chart.js'
import Highcharts from 'highcharts'

Chartkick.use(Chart).use(Highcharts)
Vue.use(Chartkick)
```

You can specify which library to use for a chart with:

```vue
<line-chart adapter="highcharts"></line-chart>
```
