### ISSUE TITLE
Chart.js Extend functionality

### ISSUE THREAD

**Issue by mesqueeb** [ankane/vue-chartkick#83]
Hi!

Great library.
I need to draw an extra line on a chart via the Extend functionality.

Similar to this fiddle but in my case a vertical line:
http://jsfiddle.net/7a4hhzge/455/

I also need a multi-color backdrop area chart based on this:
https://codepen.io/jordanwillis/pen/BWxErp?editors=1010

Do you have any advice for me how to best implement this with your library?
Thanks!

Basically, I'd need to manually edit the canvas I assume, but I don't know the best way to access the canvas. Does your library allow to extend the charts like ChartJS does?

**Comment by ankane** [comment]
Hey @mesqueeb, check out the Contributing Guide for where to get help.
