### ISSUE TITLE
Can't add additional line(s) to a line-chart

### ISSUE THREAD

**Issue by balintbabics** [ankane/vue-chartkick#85]
Hi!

I'd like to show on a line-chart two additional lines (max and average, dynamic constant values) but I couldn't find a way to add them.

I tried with :library={annotation:{annotations:[{...}]}} but it's not compiling due to it's an invalid expression and I don't really see what else should I try and how.

All I have in the code is a line:

`<line-chart :data="chartData" :stacked="true"></line-chart>`

where `chartData` is in a valid structure, which comes from the backend, and doesn't need a mapping.

**Comment by ankane** [comment]
Hey @balintbabics, check out the Contributing Guide for where to get help.

**Comment by balintbabics** [comment]
Hey @ankane, I checked it out, but at StackOverflow there is no such a tag as `vue-chartkick` so I assume if I don't get help here I won't get there too.
