### ISSUE TITLE
flickering of pie chart slices on mouseover

### ISSUE THREAD

**Issue by clandau** [ankane/vue-chartkick#87]
Pie sections will flicker on mouseover. Doesn't occur when screen is smaller. I tried to debug a bit but I am not finding the issue. 

Video of the issue, which shows it a bit slower than it actually is:
https://drive.google.com/file/d/15f0qhbjCn2KmXqVwSRsExSUUtLrdaIYh/view?usp=sharing

someone else's SO post on seemingly the same issue:
https://stackoverflow.com/questions/56601189/how-do-i-fix-chartkick-pie-chart-tooltip-flickering-when-at-max-screen-size-and

**Comment by ankane** [comment]
Hey @clandau, my initial hunch is something in the app is causing the chart to re-render continuously. Can you put together a minimal example in code to reproduce?

**Comment by clandau** [comment]
I was able to turn the trigger to selection instead of hover through the library. This will be fine until I have a chunk of time to investigate it further. Thanks!

**Comment by ankane** [comment]
Cleaning up issues
