### ISSUE TITLE
Error: Data source must be a URL for refresh

### ISSUE THREAD

**Issue by ramprakashjagadeesan** [ankane/vue-chartkick#88]
Hi,

I am receiving this issue in my console. i don't know why this error is showing in my console. any help pls 

![image](https://user-images.githubusercontent.com/47660132/65876003-09ccbe00-e3a6-11e9-9dc5-72a53e88bb2e.png)

**Comment by ankane** [comment]
Hey @ramprakashjagadeesan, please check out the Contributing Guide for where to get help.
