### ISSUE TITLE
How to change the fontSize and fontFamily?

### ISSUE THREAD

**Issue by FalkoJoseph** [ankane/vue-chartkick#9]
Can you give an example of how to change this through the props? I can't seem to figure it out.

**Comment by ankane** [comment]
Hey @FalkoJoseph, you'll need to use the `library` option. It'll be specific to whatever charting library you use.

**Comment by FalkoJoseph** [comment]
This did the trick for me

```
Chart.defaults.global.defaultFontFamily = "proxima-nova, 'Helvetica Neue', 'Helvetica', 'Arial', sans-serif";
Chart.defaults.global.defaultFontSize = 15;
Chart.defaults.global.defaultFontColor = '#2f5587';
```

Works great. 👍
