### ISSUE TITLE
problems with a date display in a line chart

### ISSUE THREAD

**Issue by matiaba** [ankane/vue-chartkick#91]
Hi guys, I'm having the following problem with chartkick:
The main idea is that it shows me a Multiple series line-chart in a modal, with the next information:
(I would like to clarify that i hardcore the data as a last resort.)

` ` <line-chart 
            :data="
            [
              {name: 'Total', data: {
                '2017-10-31': 17,
                '2017-11-06': 17,
                '2017-11-13': 16,
                '2017-11-21': 16,
                '2017-11-27': 16,
                '2017-12-04': 15,
                '2017-12-11': 15,
                '2017-12-18': 15,
                '2017-12-26': 15,
                '2018-02-19': 14,
                '2018-02-26': 14,
                '2018-03-05': 14,
                '2018-03-12': 13,
                '2018-03-19': 13,
                '2018-03-26': 13,
                '2018-04-03': 13,
                '2018-04-09': 13,
                '2018-04-16': 13,
                '2018-04-23': 12,
                '2018-04-30': 12,
                '2018-05-07': 11,
                '2018-05-14': 11,
                '2018-05-21': 10,
                '2018-05-28': 10,
                '2018-06-04': 10,
                '2018-06-11': 10,
                '2018-06-18': 10,
                '2018-06-25': 10,
                '2018-07-02': 10,
                '2018-07-10': 10,
                '2018-07-16': 10,
                '2018-07-23': 10,
                '2018-07-30': 10,
                '2018-08-06': 9,
                '2018-08-13': 10,
                '2018-08-21': 10,
                '2018-08-27': 10,
                '2018-09-03': 10,
                '2018-09-10': 10,
                '2018-09-17': 10,
                '2018-09-24': 10,
                '2018-10-01': 10,
                '2018-10-08': 10,
                '2018-10-16': 10,
                '2018-10-22': 10,
                '2018-10-29': 10,
                '2018-11-05': 10,
                '2018-11-12': 10,
                '2018-11-19': 9,
                '2018-11-26': 9,
                '2018-12-03': 9,
                '2018-12-10': 9,
                '2018-12-17': 8,
                '2018-12-24': 8,
                '2018-12-31': 8,
                '2018-01-02': 15,
                '2018-01-08': 15,
                '2018-01-15': 14,
                '2018-01-22': 14,
                '2018-01-29': 14,
                '2018-02-05': 14,
                '2018-02-14': 14,
                '2019-10-28': 6,
                '2019-10-21': 6,
                '2019-10-14': 7,
                '2019-10-07': 7,
                '2019-09-30': 7,
                '2019-09-23': 7,
                '2019-09-16': 7,
                '2019-09-09': 8,
                '2019-09-07': 8,
                '2019-09-02': 8,
                '2019-08-26': 8,
                '2019-08-20': 8,
                '2019-08-12': 8,
                '2019-08-05': 8,
                '2019-07-29': 8,
                '2019-07-22': 9,
                '2019-01-07': 8,
                '2019-01-14': 7,
                '2019-01-21': 7,
                '2019-01-28': 7,
                '2019-02-11': 7,
                '2019-02-18': 7,
                '2019-02-25': 7,
                '2019-03-04': 7,
                '2019-03-11': 7,
                '2019-03-18': 7,
                '2019-03-25': 7,
                '2019-04-01': 7,
                '2019-04-08': 7,
                '2019-04-15': 7,
                '2019-04-22': 7,
                '2019-04-29': 7,
                '2019-05-06': 6,
                '2019-05-13': 6,
                '2019-05-20': 6,
                '2019-05-27': 6,
                '2019-06-03': 6,
                '2019-06-10': 6,
                '2019-06-18': 6,
                '2019-06-24': 6,
                '2019-07-01': 6,
                '2019-07-08': 6,
                '2019-07-15': 6,
                '2019-02-04': 7,
                
                }},
              {name: 'Target', data: {
                '2017-10-31': 10,
                '2017-11-06': 10,
                '2017-11-13': 10,
                '2017-11-21': 10,
                '2017-11-27': 10,
                '2017-12-04': 10,
                '2017-12-11': 10,
                '2017-12-18': 10,
                '2017-12-26': 10,
                '2018-02-19': 10,
                '2018-02-26': 10,
                '2018-03-05': 10,
                '2018-03-12': 10,
                '2018-03-19': 10,
                '2018-03-26': 10,
                '2018-04-03': 10,
                '2018-04-09': 13,
                '2018-04-16': 13,
                '2018-04-23': 12,
                '2018-04-30': 12,
                '2018-05-07': 11,
                '2018-05-14': 11,
                '2018-05-21': 10,
                '2018-05-28': 10,
                '2018-06-04': 10,
                '2018-06-11': 10,
                '2018-06-18': 10,
                '2018-06-25': 10,
                '2018-07-02': 10,
                '2018-07-10': 10,
                '2018-07-16': 10,
                '2018-07-23': 10,
                '2018-07-30': 10,
                '2018-08-06': 9,
                '2018-08-13': 10,
                '2018-08-21': 10,
                '2018-08-27': 10,
                '2018-09-03': 10,
                '2018-09-10': 10,
                '2018-09-17': 10,
                '2018-09-24': 10,
                '2018-10-01': 10,
                '2018-10-08': 10,
                '2018-10-16': 10,
                '2018-10-22': 10,
                '2018-10-29': 10,
                '2018-11-05': 10,
                '2018-11-12': 10,
                '2018-11-19': 9,
                '2018-11-26': 9,
                '2018-12-03': 9,
                '2018-12-10': 9,
                '2018-12-17': 8,
                '2018-12-24': 8,
                '2018-12-31': 8,
                '2018-01-02': 15,
                '2018-01-08': 15,
                '2018-01-15': 14,
                '2018-01-22': 14,
                '2018-01-29': 14,
                '2018-02-05': 14,
                '2018-02-14': 14,
                '2019-10-28': 6,
                '2019-10-21': 6,
                '2019-10-14': 7,
                '2019-10-07': 7,
                '2019-09-30': 7,
                '2019-09-23': 7,
                '2019-09-16': 7,
                '2019-09-09': 8,
                '2019-09-07': 8,
                '2019-09-02': 8,
                '2019-08-26': 8,
                '2019-08-20': 8,
                '2019-08-12': 8,
                '2019-08-05': 8,
                '2019-07-29': 8,
                '2019-07-22': 9,
                '2019-01-07': 8,
                '2019-01-14': 7,
                '2019-01-21': 7,
                '2019-01-28': 7,
                '2019-02-11': 7,
                '2019-02-18': 7,
                '2019-02-25': 7,
                '2019-03-04': 7,
                '2019-03-11': 7,
                '2019-03-18': 7,
                '2019-03-25': 7,
                '2019-04-01': 7,
                '2019-04-08': 7,
                '2019-04-15': 7,
                '2019-04-22': 7,
                '2019-04-29': 7,
                '2019-05-06': 6,
                '2019-05-13': 6,
                '2019-05-20': 6,
                '2019-05-27': 6,
                '2019-06-03': 6,
                '2019-06-10': 6,
                '2019-06-18': 6,
                '2019-06-24': 6,
                '2019-07-01': 6,
                '2019-07-08': 6,
                '2019-07-15': 6,
                '2019-02-04': 7,
                }}]"
            :curve="false"
            :points="false"
            :discrete="false"
            :colors="['#4bb2bd', '#ea3732']"
            height="150px"
            suffix= "%"
            />``

the graphis shows perfectly BUT the dates don't appear 
![imagen](https://user-images.githubusercontent.com/42469052/68152516-94af5400-ff22-11e9-82fd-00a764f95135.png)
i tried everything but i don't know what`s wrong. put `discrete: true` can NOT be an option. 
I need it to be `discreet: false` because I must handle a lot of information from several dates

I hope you can help me

**Comment by ankane** [comment]
Hey @matiaba, unfortunately, I'm not able to reproduce with that code.

![Screen Shot 2019-11-05 at 1 21 40 PM](https://user-images.githubusercontent.com/220358/68247305-620f6500-ffcf-11e9-9267-879de7ce1502.png)

I'd make sure you're on the latest versions of Vue Chartkick and Chart.js and not overriding the global settings somewhere.
