### ISSUE TITLE
Passing options through ":library{}" not working

### ISSUE THREAD

**Issue by u-amine** [ankane/vue-chartkick#92]
Hey,

I tried to hide the xAxis as you would do it in plain chart.js and wanted to forward the params through (as mentioned in the documentation) `:library={}` like [here](https://jsfiddle.net/z38yejs1/2/). But it did work. 

Any guess? 

Best!

**Comment by ankane** [comment]
Hey @u-amine, if you remove the `options` part and change `xAxis` to `xAxes`, it'll work as expected.
