### ISSUE TITLE
Receiving and displaying multiple datasets after API call

### ISSUE THREAD

**Issue by u-amine** [ankane/vue-chartkick#93]
Hi,

I receive arrays from an API in a JSON format. I want to merge them into the nested array called which consists of objects `graphData`. How do I extend the data object by one entry?

```
mounted() {

   var i = 0;
   const axios = require('axios');
    //Usage
    axios.get("https://3.11.40.69:9001/app/usageUnitForCustomer/1521/2019-12-30/2020-12-30")
      .then(response => {
        const time = response.data.event_time; //["2019-12-30T14:06:21.000Z", "2019-12-30T14:06:21.000Z"]
        const unit = response.data.unit; //[44.67, 75.89]
        for (i = 0; i < 1; i++) {
          if (time[i] !== time[i + 1]) {
            this.graphData[1].data[time[i].toString()] = unit[i];
          }
        } 
      })
    //Revenue
    axios.get("https://3.11.40.69:9001/app/revenueUnitForMachine/345/2019-12-30/2020-12-30")
      .then(response => {
        const time = response.data.event_time; //["2019-12-30T14:06:21.000Z", "2019-12-30T14:06:21.000Z"]
        const unit = response.data.revenue; //[44, 75]
        for (i = 0; i < 10; i++) {
          if (time[i] !== time[i + 1]) {
            this.graphData[0].data[time[i].toString()] = unit[i];
          }
        } 

      })
  },
  data() {
      return {
        graphData: [
          {name: 'Revenue', data: {}},
          {name: 'Usage', data: {}}
        ]
      }
    }
```

After executing the above code both data objects contain data and this also what the vue dev tools show: 

![image](https://user-images.githubusercontent.com/26627366/72224324-b27be380-3579-11ea-868b-a10677e8857c.png)

But the graphs are not displaying. I am not sure if there is an error in the code or in the library, because there is also no error message. 

Thanks!

**Comment by ankane** [comment]
Hey @u-amine, it looks like you're updating the objects in-place, which doesn't trigger Vue updates. https://vuejs.org/v2/guide/list.html#Object-Change-Detection-Caveats

Try `Vue.set` or fully replacing `graphData`.

**Comment by u-amine** [comment]
Hey @ankane,

I tried this out: `this.$set(this.graphData[0].data, [time[i].toString()], unit[i]);`, but the error remains.

**Comment by ankane** [comment]
I don't think that syntax is exactly correctly. Unfortunately, I don't have the bandwidth to help with app-specific issues. Check out the Contributing Guide for where to get additional help.
