### ISSUE TITLE
[Idea] Add ability to include headers to endpoints

### ISSUE THREAD

**Issue by youngchan1694** [ankane/vue-chartkick#94]
Hello.
Our current project uses chartkick to render charts by providing them endpoints to our backend. However, most of our endpoints currently use JWT authentication tokens in order to access that data, would it be possible to add a a prop that takes in headers and/or other backend settings? If not, either the charts don't render due to no access and throw a 401 or we have to unlock those certain endpoints.

Thanks!

**Comment by ankane** [comment]
Hey @youngchan1694, thanks for the suggestion!

You can currently use a function for `:data` to customize authentication, so I'd like to hold off on this for now. If there's demand in non-JS versions (which don't have the ability to use functions), I can see a `headers` option making sense.

**Comment by youngchan1694** [comment]
Ah, okay I appreciate it. I couldn't find an example of passing a function into the `:data` prop in the docs, is there someplace that I could see a working version? Thanks!

**Comment by ankane** [comment]
Docs are here: https://github.com/ankane/vue-chartkick#data
