### ISSUE TITLE
stepSize not working in line chart

### ISSUE THREAD

**Issue by griffoe** [ankane/vue-chartkick#95]
Hi, Trying to set stepSize using options through :library prop and it doesn't seem to work ? It works for max, min etc but not stepSize - any ideas ?

:library="{
                                                scales:{
                                                        yAxes:[{
                                                                ticks:{
                                                                        stepSize:0.5
                                                                }
                                                        }]
                                                }
                                        
                                        }"

Thanks!

**Comment by ankane** [comment]
Hey @griffoe, it's due to a default `maxTicksLimit`. You can disable it with `maxTicksLimit: null`.

**Comment by griffoe** [comment]
Thankyou, worked fine.

**Comment by hamzakabeercs** [comment]
Thanks buddy, it works
