### ISSUE TITLE
Google charts ?

### ISSUE THREAD

**Issue by griffoe** [ankane/vue-chartkick#96]
Hi,

Any quick pointers to chart tag names and /or settings for various adapter's. For example <pie-chart> works fine along with many other charts but <gauge> or <maps> doesn't work for google adapter?

Thanks!

**Comment by griffoe** [comment]
Sorry above comment excluded my tags. pie-chart , line-chart works fine but gauge , maps doesn't work? Are my tags correct ?

**Comment by ankane** [comment]
Hey @griffoe, all of the supported chart types are in the readme.
