### ISSUE TITLE
How to pass data for stacked chart

### ISSUE THREAD

**Issue by sonisaurabh19** [ankane/vue-chartkick#97]
Hi,
Thanks for on library!

I have tried many options, but not able to create a column or bar chart with stacked representation. I guess I don't know how should the data be presented. I tried the following:
```
[
        [
            "Monday",
            2,
            10
        ],
]
//
[
        [
            "Monday",
            [2],
            [10]
        ],
]
//
[
        [
            "Monday",
            [
              2,
             10
            ]
        ],
]
```
Appreciate the help

**Comment by ankane** [comment]
Hey @sonisaurabh19, check out the Contributing Guide for where to get help.

**Comment by bborn** [comment]
You need to pass the data in this format:

```
chartData = [
        {
          name: "Impressions",
          data: [["Metric", 1000]],
        },
        {
          name: "Video Views",
          data: [["Metric", 1000]],
        },
        {
          name: "Impressions",
          data: [["Metric", 1000]],
        },
      ];
<bar-chart :stacked="true" :data="chartData"></bar-chart>
```

Note how each object within the data array has the same `name` attribute. That's what will make them stack.

Code sandbox here:

https://codesandbox.io/s/black-fire-14loc?from-embed=&file=/src/App.vue
